# .forge-lock.hcl — DO NOT EDIT MANUALLY
# Generated by forge. Changes will be overwritten on sync.

blueprint {
  registry_url = "/Users/donaldgifford/code/forge-registry"
  name         = "std-new"
  path         = "std/new"
}

created_at    = "2026-05-21T09:33:21.853068Z"
last_synced   = "2026-05-21T09:33:21.853068Z"
forge_version = "0.7.0"

variables {
  git_host               = "github.com"
  git_provider           = "github"
  license                = "Apache-2.0"
  project_description    = "Claudelint Github Action"
  project_name           = "claudelint-action"
  project_org            = "donaldgifford"
  renovate_config_prefix = "github"
}

default ".checkmake.ini" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:123f1dc4a0f6e608cd57546d72894791ef719ad07cc0fdd53016d57557cb9284"
}

default ".docz.yaml" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:f3fb2387d31e3b07fa2a1efdf3e974814b13113c763a7b82d7425eb2967bbcfc"
}

default ".makefmt.yml" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:c56b8f4be0b7722a0e8fda97faf4d8c29e4ff75193acf663bf5a5b0e7fbf4808"
}

default ".markdownlint.yaml" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:dc9182bd0b399616bd2b6933eb4b2a756674cedb43dbea914cf61f9180e3fc92"
}

default ".prettierrc.yaml" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:402823be7f1d14a6bdd7a8801c6392f7b8e74675e842aa355fccc07766b538d8"
}

default ".yamlfmt.yml" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:d214a4f56043cad5e01bd70e3530155df3bf7372bd2571aba87bcee0c1dcca73"
}

default ".yamllint.yml" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:3f8575b37ea4a59395110326535d36573208fc6495ac47e357512fa7b8bbf7a9"
}

default ".gitkeep" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
}
