[tools]

# Repo utilities
just = "latest"

# Formatters and linters
# renovate: datasource=github-releases depName=DavidAnson/markdownlint-cli2
markdownlint-cli2 = "0.18.1"
# renovate: datasource=github-releases depName=google/yamlfmt
yamlfmt = "0.20.0"
# renovate: datasource=github-tags depName=adrienverge/yamllint
yamllint = "1.38.0"
# renovate: datasource=npm depName=prettier
prettier = "3.7.4"
"github:donaldgifford/makefmt" = "latest"
checkmake = "latest"
git-cliff = "latest"
actionlint = "latest"

# tools
# renovate: datasource=github-releases depName=mikefarah/yq
yq = "4.48.1"
jq = "latest"
"github:donaldgifford/docz" = "latest"
"github:donaldgifford/claudelint" = "latest"
